name: CI Build, Test, and Package
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show repository structure
        run: tree -L 2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            make \
            build-essential \
            tree
      - name: Build
        run: |
          make clean
          mkdir -p build
          make -j$(nproc) V=1
          echo "Build artifacts:"
          ls -l build/
      - name: Verify headers
        run: |
          if [ -d "include" ]; then
            echo "Header files found:"
            ls -l include/
          else
            echo "Warning: include/ directory not found - creating empty directory"
            mkdir -p include
          fi
      - name: Run tests
        run: |
          cd tests && make clean && make && make test
  package:
    needs: build-and-test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install packaging tools
        run: sudo apt-get install -y tree
      - name: Prepare directories
        run: |
          mkdir -p dist/{lib,include}
          echo "Directory structure prepared:"
          tree dist/
      - name: Package artifacts
        run: |
          # 1. Copy headers if they exist
          if [ -d "include" ] && [ "$(ls -A include)" ]; then
            echo "Copying headers..."
            cp -r include/* dist/include/
          else
            echo "Warning: No headers to copy"
          fi

          # 2. Copy static library
          if [ -f "build/libcrypto.a" ]; then
            echo "Copying static library..."
            cp build/libcrypto.a dist/lib/
          else
            echo "Warning: Static library not found"
          fi

          # 3. Handle shared libraries
          if ls build/libcrypto.so* 1>/dev/null 2>&1; then
            echo "Copying shared libraries..."
            cp build/libcrypto.so* dist/lib/
            cd dist/lib
            sofile=$(ls libcrypto.so.* | head -n1)
            ln -sf "$sofile" libcrypto.so
            cd -
          else
            echo "Error: No shared libraries found in build/"
            ls -l build/
            exit 1
          fi

          # 4. Create pkg-config file
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Creating pkg-config file for version $VERSION"
          cat > dist/libcrypto.pc <<EOF
          prefix=/usr/local
          libdir=\${prefix}/lib
          includedir=\${prefix}/include

          Name: libcrypto
          Description: Educational crypto library
          Version: $VERSION
          Libs: -L\${libdir} -lcrypto
          Cflags: -I\${includedir}
          EOF

          # 5. Verify package
          echo "Final package contents:"
          tree dist/
          echo "pkg-config file contents:"
          cat dist/libcrypto.pc
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libcrypto-${{ github.ref_name }}
          path: dist/
      - name: Create release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            dist/lib/*
            dist/include/*
            dist/libcrypto.pc
