name: Crypto CI/CD
on:
  push:
    tags: ['v*.*.*'] # Trigger on version tags (e.g., v1.0.0)
  pull_request:
    branches: [master]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${GITHUB_REF#refs/tags/v} # Extracts version from tag (v1.0.0 → 1.0.0)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang
      - name: Build
        run: |
          make clean
          make
      - name: Run tests
        run: |
          cd tests && make clean && make && make test
      - name: Verify build artifacts
        run: |
          echo "Build directory contents:"
          ls -l build/
          echo "Include directory contents:"
          ls -l include/
      - name: Package artifacts
        run: |
          # Create distribution directories
          mkdir -p dist/{lib,include}

          # Copy libraries (with error handling)
          if [ -f "build/libcrypto.so.$VERSION" ]; then
            cp build/libcrypto.so.$VERSION dist/lib/
            ln -s libcrypto.so.$VERSION dist/lib/libcrypto.so
          else
            echo "Error: Shared library not found!"
            exit 1
          fi

          if [ -f "build/libcrypto.a" ]; then
            cp build/libcrypto.a dist/lib/
          else
            echo "Error: Static library not found!"
            exit 1
          fi

          # Copy headers (preserve directory structure)
          if [ -d "include" ]; then
            mkdir -p dist/include
            cp -r include/* dist/include/
          else
            echo "Error: Include directory not found!"
            exit 1
          fi

          # Create pkg-config file
          mkdir -p dist/pkgconfig
          cat > dist/pkgconfig/libcrypto.pc <<EOF
          prefix=/usr/local
          libdir=\${prefix}/lib
          includedir=\${prefix}/include

          Name: libcrypto
          Description: Educational crypto library
          Version: $VERSION
          Libs: -L\${libdir} -lcrypto
          Cflags: -I\${includedir}
          EOF

          # Verify final package
          echo "Package contents:"
          tree dist/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libcrypto-${{ env.VERSION }}-linux
          path: dist/
          retention-days: 1
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: "Version ${{ env.VERSION }}"
          body: "Pre-built cryptographic library package"
          files: |
            dist/lib/*
            dist/include/*
            dist/pkgconfig/libcrypto.pc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
