name: CI Build, Test, and Package
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            make \
            build-essential \
            tree
      - name: Build
        run: |
          make clean
          mkdir -p build
          make -j$(nproc)
          echo "Build artifacts:"
          ls -l build/
      - name: Run tests
        run: |
          cd tests && make clean && make && make test
  package:
    needs: build-and-test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Determine version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Packaging version: ${VERSION}"
      - name: Package artifacts
        run: "# Create directory structure\nmkdir -p dist/{lib,include,pkgconfig}\n\n# Handle shared library\nif [ -f \"build/libcrypto.so\" ]; then\n  echo \"Found shared library\"\n  cp build/libcrypto.so dist/lib/\n  \n  # Only create versioned copy and symlink if version is specified\n  if [ -n \"$VERSION\" ]; then\n    cp build/libcrypto.so dist/lib/libcrypto.so.$VERSION\n    cd dist/lib\n    ln -sf libcrypto.so.$VERSION libcrypto.so\n    cd -\n  fi\nelse\n  echo \"Error: Shared library not found\"\n  ls -l build/\n  exit 1\nfi\n\n# Handle static library\nif [ -f \"build/libcrypto.a\" ]; then\n  echo \"Copying static library\"\n  cp build/libcrypto.a dist/lib/\nelse\n  echo \"Error: Static library not found\"\n  exit 1\nfi\n\n# Handle headers\nif [ -d \"include\" ] && [ \"$(ls -A include)\" ]; then\n  echo \"Copying headers\"\n  cp -r include/* dist/include/\nelse\n  echo \"Error: No headers found in include/\"\n  exit 1\nfi\n\n# Create pkg-config file\ncat > dist/pkgconfig/libcrypto.pc <<EOF\nprefix=/usr/local\nlibdir=\\${prefix}/lib\nincludedir=\\${prefix}/include\n\nName: libcrypto\nDescription: Educational crypto library\nVersion: $VERSION\nLibs: -L\\${libdir} -lcrypto\nCflags: -I\\${includedir}\nEOF\n\n# Verify package\necho \"Final package contents:\"\ntree dist/\n"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libcrypto-${{ env.VERSION }}
          path: dist/
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            dist/lib/*
            dist/include/*
            dist/pkgconfig/libcrypto.pc
