name: CI Build, Test, and Package
on:
  push:
    branches: [main]
    tags: ['v*'] # Triggers on version tags (v1.1.1)
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            make \
            build-essential \
            binutils
      - name: Build with debug info
        run: |
          mkdir -p build
          make -j$(nproc) V=1 2>&1 | tee build.log
          echo "Build artifacts:"
          ls -l build/
      - name: Run tests
        run: |
          cd tests
          make clean
          make
          make test
  package:
    needs: build-and-test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            make \
            tree
      - name: Rebuild for packaging
        run: |
          make clean
          mkdir -p build
          make -j$(nproc)
      - name: Verify build artifacts
        run: |
          echo "Build directory contents:"
          ls -l build/
          [ -f "build/libcrypto.a" ] || echo "Error: libcrypto.a missing!"
          ls build/libcrypto.so* || echo "Error: No libcrypto.so files found!"
      - name: Package artifacts
        run: |
          mkdir -p dist/{lib,include}

          # Static library
          if [ -f "build/libcrypto.a" ]; then
            cp build/libcrypto.a dist/lib/
          else
            echo "Warning: Static library not found"
          fi

          # Shared libraries
          for sofile in build/libcrypto.so*; do
            [ -e "$sofile" ] && cp "$sofile" dist/lib/
          done

          # Create symlink
          cd dist/lib && \
          sofile=$(ls libcrypto.so.* | head -n1) && \
          ln -sf "$sofile" libcrypto.so

          # Headers
          cp -r include/libcrypto/* dist/include/

          # pkg-config
          VERSION=${GITHUB_REF#refs/tags/v}
          cat > dist/libcrypto.pc <<EOF
          prefix=/usr/local
          libdir=\${prefix}/lib
          includedir=\${prefix}/include/libcrypto

          Name: libcrypto
          Description: Educational crypto library
          Version: $VERSION
          Libs: -L\${libdir} -lcrypto
          Cflags: -I\${includedir}
          EOF

          echo "Package contents:"
          tree dist/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libcrypto-${{ github.ref_name }}
          path: dist/
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            dist/lib/libcrypto.*
            dist/include/**
            dist/libcrypto.pc
